### ISSUE TITLE
History scan is possible?

### ISSUE THREAD

**Issue by lychee1-rb** [secretlint/secretlint#211] opened 2021-11-10 05:58 UTC
Now I'm using Secretlint to detect secrets in github repositroy and I want to detect them not only in main branch but in other branch and history too.
Is Secretlint possible to scan a repository including all revisions?

**Comment by azu** [comment] 2021-11-10 06:13
#34 Not Yet.

https://github.com/secretlint/secretlint/issues/34#issuecomment-596162793
Probably, this oneliner will work, but we want to provide more easy understandable tool.

For example, it is following command.
```
npx @secretlint/history-scan
```

**Comment by azu** [comment] 2022-03-05 12:56
Duplicate of #34

**Closed by azu** 2022-03-05 12:56 UTC
Labels: Type: Question
